### ISSUE TITLE
addParam -> param, addHeader -> header

### ISSUE THREAD

**Issue by eveliotc** [yayuhh/Projectile#2]
Nice builder! yet could be nicer:

``` java
Projectile.draw(this).aim("http://www.myapiurl/users")
                .method(POST)
                .param("user", "nick")
                .params(paramsMap)
                .timeout(5000)
```

same with headers

**Comment by nicktate** [comment]
@eveliotc I was on the fence for the header and parameter builder methods and personally preferred your suggestion. The team at my company preferred `addParam` versus `param`, so it found its way in here as an artifact of that. Glad you like the builder, I'll schedule adding in the aliases for the next version.

**Comment by nicktate** [comment]
Added in version 1.0.3 (should be on maven central in a few hours)
